# Generated by Django 3.2 on 2022-04-06 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deudor', '0011_auto_20220405_1804'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionAbogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gestionAbogado', models.DateTimeField(auto_now_add=True)),
                ('actuaciones_proceso', models.CharField(blank=True, max_length=200)),
                ('fecha_inicia_termino', models.DateField(blank=True, null=True)),
                ('fecha_finaliza_termino', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('fecha_control', models.DateField(blank=True, null=True)),
                ('calificacion_viabilidad', models.CharField(blank=True, choices=[('0', 'Viable'), ('1', 'No viable')], max_length=2)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, upload_to='gestionAbogado')),
                ('deudores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestionAbogado_deudor', to='deudor.deudor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
