# Generated by Django 3.2 on 2022-03-07 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deudor', '0010_alter_deudor_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionAbogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gestionAbogado', models.DateTimeField(auto_now_add=True)),
                ('califiacion_viabilidad', models.CharField(choices=[('0', 'Viable'), ('1', 'No viable')], max_length=2)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, upload_to='gestionAbogado')),
                ('archivo2', models.FileField(blank=True, upload_to='gestionAbogado')),
                ('archivo3', models.FileField(blank=True, upload_to='gestionAbogado')),
                ('archivo4', models.FileField(blank=True, upload_to='gestionAbogado')),
                ('archivo5', models.FileField(blank=True, upload_to='gestionAbogado')),
                ('archivo6', models.FileField(blank=True, upload_to='gestionAbogado')),
                ('deudores', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestionAbogado_deudor', to='deudor.deudor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
