# Generated by Django 3.2 on 2022-07-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
