# Generated by Django 3.2 on 2022-07-11 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresaSocia', '0003_remove_empresasocia_deudores'),
        ('sede', '0002_alter_sede_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='empresaSocia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresaSocia_sede', to='empresaSocia.empresasocia'),
        ),
    ]
