# Generated by Django 3.2 on 2021-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_fijo_add', models.CharField(blank=True, max_length=15, null=True)),
                ('celular_add', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_add', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel_empresa_add', models.CharField(blank=True, max_length=12, null=True)),
                ('celular_empresa_add', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
