# Generated by Django 3.2 on 2021-05-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adicional', '0003_adicionado_conyugue'),
        ('deudor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionado',
            name='deudores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deudor.deudor'),
        ),
    ]
