# Generated by Django 3.2 on 2021-05-20 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deudor', '0002_deudor_usuarios'),
        ('adicional', '0005_adicionado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionado',
            name='deudores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adicionado_deudor', to='deudor.deudor'),
        ),
    ]
