# Generated by Django 3.2 on 2021-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codeudor',
            fields=[
                ('codigo_codeudor', models.BigIntegerField(unique=True)),
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_exp_cedula', models.DateField()),
                ('ocupacion', models.CharField(max_length=60)),
                ('profesion', models.CharField(max_length=60)),
                ('nivel_estudios', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tel_fijo', models.PositiveIntegerField(blank=True, default=0)),
                ('celular', models.CharField(max_length=10)),
                ('tel_fijo2', models.PositiveIntegerField(blank=True, default=0)),
                ('celular2', models.CharField(blank=True, max_length=10)),
                ('eps', models.CharField(max_length=60)),
            ],
        ),
    ]
