# Generated by Django 3.2 on 2021-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('codeudor', '0001_initial'),
        ('deudor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeudor',
            name='deudores',
            field=models.ManyToManyField(to='deudor.Deudor'),
        ),
    ]
