# Generated by Django 3.2 on 2021-05-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0009_credito_normalizado'),
        ('codeudor', '0002_codeudor_deudores'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeudor',
            name='credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credito.credito'),
        ),
    ]
