# Generated by Django 3.2 on 2021-05-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0009_credito_normalizado'),
        ('codeudor', '0003_codeudor_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeudor',
            name='credito',
        ),
        migrations.AddField(
            model_name='codeudor',
            name='credito',
            field=models.ManyToManyField(to='credito.Credito'),
        ),
    ]
