# Generated by Django 3.2 on 2021-05-21 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeudor', '0005_auto_20210520_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeudor',
            name='credito',
        ),
    ]
