# Generated by Django 3.2 on 2021-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('codigo_credito', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha_corte', models.DateField()),
                ('segmento_riesgo', models.CharField(max_length=2)),
                ('nivel_riesgo', models.CharField(max_length=2)),
                ('analisis_contencion', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('forma_pago', models.CharField(max_length=20)),
                ('clase_cartera', models.CharField(max_length=30)),
                ('linea_credito', models.CharField(max_length=30)),
                ('dias_mora', models.PositiveSmallIntegerField()),
                ('franja_mora', models.CharField(max_length=30)),
                ('valor_credito', models.BigIntegerField()),
                ('plazo_total_meses', models.PositiveSmallIntegerField()),
                ('fecha_desembolso', models.DateField()),
                ('cuotas_vencidad', models.PositiveSmallIntegerField()),
                ('cuotas_pagadas', models.PositiveSmallIntegerField()),
                ('saldo_insoluto', models.BigIntegerField()),
                ('valor_cuota', models.IntegerField()),
                ('valor_cuota_mas_otros', models.IntegerField()),
                ('pago_min_estar_al_dia', models.IntegerField()),
                ('pago_total', models.BigIntegerField()),
                ('pago_min_liberar_provision', models.IntegerField()),
                ('valor_total_provision', models.BigIntegerField()),
                ('dia_corte', models.SmallIntegerField()),
                ('saldo_cuenta_ahorros', models.BigIntegerField()),
                ('saldo_aportes_sociales', models.BigIntegerField()),
                ('valor_disponible_cupo_rotativo', models.IntegerField()),
                ('aportes_sociales_vencidos', models.IntegerField()),
                ('valor_seguros_vencidos', models.IntegerField()),
                ('otros_vencidos', models.IntegerField()),
                ('capital_obligaciones_vencidas', models.IntegerField()),
                ('intereses_vencidos', models.IntegerField()),
                ('intereses_mora', models.IntegerField()),
                ('valores_gastos_prejuridico', models.IntegerField()),
                ('valores_gastos_juridico', models.IntegerField()),
            ],
        ),
    ]
