# Generated by Django 3.2 on 2021-05-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0002_credito_deudor'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='vencido',
            field=models.BooleanField(default=False),
        ),
    ]
