# Generated by Django 3.2 on 2021-05-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0004_alter_credito_dias_mora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='cuotas_vencidad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='credito',
            name='dias_mora',
            field=models.SmallIntegerField(default=0),
        ),
    ]
