# Generated by Django 3.2 on 2021-05-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0005_auto_20210519_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='dias_mora',
            field=models.IntegerField(),
        ),
    ]
