# Generated by Django 3.2 on 2021-05-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0006_alter_credito_dias_mora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='dias_mora',
            field=models.FloatField(),
        ),
    ]
