# Generated by Django 3.2 on 2021-05-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0007_alter_credito_dias_mora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credito',
            old_name='cuotas_vencidad',
            new_name='cuotas_vencidas',
        ),
        migrations.AlterField(
            model_name='credito',
            name='dias_mora',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
