# Generated by Django 3.2 on 2021-05-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0009_credito_normalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='codigo_credito',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
