# Generated by Django 3.2 on 2021-05-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeudor', '0006_remove_codeudor_credito'),
        ('credito', '0012_auto_20210520_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='codeudores',
            field=models.ManyToManyField(blank=True, null=True, to='codeudor.Codeudor'),
        ),
    ]
