# Generated by Django 3.2 on 2021-08-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0015_alter_credito_codeudores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='aportes_sociales_vencidos',
        ),
    ]
