# Generated by Django 3.2 on 2021-05-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deudor', '0001_initial'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='deudores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestion_deudor', to='deudor.deudor'),
        ),
        migrations.AddField(
            model_name='gestion',
            name='estado_acuerdo_pago',
            field=models.CharField(blank=True, choices=[('0', 'Cumplido'), ('1', 'No cumplido')], max_length=2, null=True),
        ),
    ]
