# Generated by Django 3.2 on 2021-05-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_gestion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='castigada',
            field=models.BooleanField(default=False),
        ),
    ]
