# Generated by Django 3.2 on 2021-05-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_gestion_castigada'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestion',
            name='evidencia',
            field=models.FileField(blank=True, upload_to='acuerdos'),
        ),
    ]
