# Generated by Django 3.2 on 2021-12-04 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_gestion_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='castigada',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='estado_acuerdo_pago',
        ),
    ]
