# Generated by Django 3.2 on 2021-05-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_insoluto_mes',
            field=models.BigIntegerField(default=0),
        ),
    ]
