# Generated by Django 3.2 on 2021-06-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_total_insoluto_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_email',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Password de email'),
        ),
    ]
