# Generated by Django 3.2 on 2021-06-27 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_pass_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_day_month',
            field=models.BooleanField(default=False),
        ),
    ]
