# Generated by Django 3.2 on 2021-06-27 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_first_day_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_day_month',
        ),
    ]
