# Generated by Django 3.2 on 2021-12-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_first_day_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='position',
            new_name='ocupation',
        ),
    ]
