# Generated by Django 3.2 on 2022-03-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_position_user_ocupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ocupation',
            field=models.CharField(blank=True, choices=[('0', 'Operario'), ('1', 'Administrador de local'), ('2', 'Administrador de region'), ('3', 'Super administrador'), ('4', 'Abogado')], max_length=1),
        ),
    ]
