# Generated by Django 3.2 on 2021-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('cargo_empleado', models.CharField(max_length=70)),
                ('fecha_ingreso_laboral', models.DateField()),
                ('tipo_contrato', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=70)),
                ('barrio', models.CharField(max_length=70)),
                ('ciudad', models.CharField(max_length=70)),
                ('departamento', models.CharField(max_length=70)),
                ('correo_laboral', models.EmailField(max_length=254)),
                ('tel_fijo', models.CharField(blank=True, max_length=7)),
                ('celular', models.CharField(max_length=10)),
            ],
        ),
    ]
