# Generated by Django 3.2 on 2021-05-20 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deudor', '0002_deudor_usuarios'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='deudor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deudor.deudor'),
        ),
    ]
