# Generated by Django 3.2 on 2021-05-20 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deudor', '0002_deudor_usuarios'),
        ('empresa', '0002_empresa_deudor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='deudor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_deudor', to='deudor.deudor'),
        ),
    ]
