# Generated by Django 3.2 on 2022-07-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deudor', '0011_auto_20220405_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaSocia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('deudores', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresaSocia_deudor', to='deudor.deudor')),
            ],
        ),
    ]
