# Generated by Django 3.2 on 2021-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deudor',
            fields=[
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('codigo_deudor', models.BigIntegerField(unique=True)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_exp_cedula', models.DateField()),
                ('ocupacion', models.CharField(max_length=60)),
                ('profesion', models.CharField(max_length=60)),
                ('nivel_estudios', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('ingresos_reportados', models.BigIntegerField()),
                ('personas_a_cargo', models.PositiveIntegerField(default=0)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tel_fijo', models.CharField(blank=True, max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('tel_fijo2', models.CharField(blank=True, max_length=15)),
                ('celular2', models.CharField(blank=True, max_length=15)),
                ('eps', models.CharField(max_length=60)),
                ('total_insolutos', models.BigIntegerField(blank=True, null=True)),
                ('total_provisiones', models.BigIntegerField(blank=True, null=True)),
                ('fecha_nueva_accion', models.DateField(blank=True, null=True)),
                ('hora_nueva_accion', models.TimeField(blank=True, null=True)),
                ('nueva_accion', models.CharField(blank=True, max_length=200, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('contador_gestiones', models.IntegerField(default=0)),
                ('full_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
