# Generated by Django 3.2 on 2021-05-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deudor', '0002_deudor_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='castigado',
            field=models.BooleanField(default=False),
        ),
    ]
