# Generated by Django 3.2 on 2021-05-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deudor', '0003_deudor_castigado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudor',
            name='total_insolutos',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='total_provisiones',
            field=models.BigIntegerField(default=0),
        ),
    ]
