# Generated by Django 3.2 on 2021-05-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deudor', '0004_auto_20210527_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='dia_max_corte',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deudor',
            name='dia_max_mora',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deudor',
            name='estado_inicial',
            field=models.CharField(default='x', max_length=20),
            preserve_default=False,
        ),
    ]
