# Generated by Django 3.2 on 2021-07-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deudor', '0006_alter_deudor_estado_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='total_credito',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deudor',
            name='total_estar_al_dia',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deudor',
            name='total_liberar_provision',
            field=models.BigIntegerField(default=0),
        ),
    ]
