# Generated by Django 3.2 on 2021-08-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deudor', '0007_auto_20210714_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='aportes_sociales_vencidos',
            field=models.IntegerField(default=0),
        ),
    ]
