# Generated by Django 3.2 on 2022-03-06 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deudor', '0009_auto_20210910_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudor',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='deudor_usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
