# Generated by Django 3.2 on 2022-04-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deudor', '0010_alter_deudor_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudor',
            name='total_credito',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='total_estar_al_dia',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='total_insolutos',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='total_liberar_provision',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='deudor',
            name='total_provisiones',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
