# Generated by Django 3.2 on 2022-07-11 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresaSocia', '0003_remove_empresasocia_deudores'),
        ('deudor', '0011_auto_20220405_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='empresaSocia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresaSocia_deudor', to='empresaSocia.empresasocia'),
        ),
    ]
