# Generated by Django 3.2 on 2022-07-11 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0003_sede_empresasocia'),
        ('deudor', '0012_deudor_empresasocia'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudor',
            name='sede',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sede_deudor', to='sede.sede'),
        ),
    ]
