# Generated by Django 3.2 on 2021-05-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcuerdosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('valor_compromiso', models.BigIntegerField()),
                ('forma_pago', models.CharField(max_length=50)),
                ('evidencia', models.FileField(blank=True, upload_to='acuerdos')),
                ('fecha_1', models.DateField(null=True)),
                ('fecha_2', models.DateField(blank=True, null=True)),
                ('fecha_3', models.DateField(blank=True, null=True)),
                ('valor_compromiso_2', models.BigIntegerField(blank=True, null=True)),
                ('valor_compromiso_3', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
