# Generated by Django 3.2 on 2021-05-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acuerdo', '0001_initial'),
        ('deudor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdospago',
            name='deudores',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acuerdo_deudor', to='deudor.deudor'),
        ),
    ]
