# Generated by Django 3.2 on 2021-12-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuerdo', '0005_alter_acuerdospago_estado_del_acuerdo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdospago',
            name='estado_del_acuerdo',
            field=models.CharField(default='En proceso', max_length=50),
        ),
    ]
