# Generated by Django 3.2 on 2021-12-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acuerdo', '0007_remove_acuerdospago_cumplido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdospago',
            name='estado_del_acuerdo',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
