# Generated by Django 3.2 on 2021-05-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deudor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('tipo_pago_aplicado', models.CharField(max_length=200)),
                ('forma_pago', models.CharField(max_length=200)),
                ('valor_pago', models.BigIntegerField()),
                ('no_recibo_pago', models.IntegerField()),
                ('valor_abono_saldo_credito', models.BigIntegerField()),
                ('valor_abono_intereses_corrientes', models.IntegerField()),
                ('valor_abono_intereses_moratorios', models.IntegerField()),
                ('valor_gastos_cobranza', models.IntegerField()),
                ('valor_abono_honorarios', models.IntegerField()),
                ('deudores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deudor.deudor')),
            ],
        ),
    ]
